### ISSUE TITLE
JWT mechanism implementation

### ISSUE THREAD

**Issue by mayurhyphenOs** [hyphenOs/pkt-trail-fe-api-server#2]

**Comment by gabhijit** [comment]
https://django-rest-framework-simplejwt.readthedocs.io/en/latest/getting_started.html - Check this library - 

Overall the basic flow should be as follows - 

1. After github authentication is completed - Get the JWT token - Right now just working with access-token is good enough - no need to go for refresh token.

2. This is to be sent to front-end and front-end should save it to `localStorage` and then use it for making the requests.

**Comment by mayurhyphenOs** [comment]
JWT Implementation Approach:

1. code and client_id sent by the client are used to fetch access-token from github api. 
2. onSuccess access_token: server will generate a JSON Web Token (called JWT onwards) and will send it back to the client
3. Client will store this token in local or session storage.
3. Client will send this token in header like "Authorization": "token <JWT_TOKEN>" of every request
4. Server will validate JWT from request header using signature part of token
5. onSuccess jwt_validation: server will process the request

**Comment by gabhijit** [comment]
For validation etc. the `simplejwt` library itself provides methods. Please use those.

**Comment by mayurhyphenOs** [comment]
Okay
